import { StylesProvider } from './styles-provider'
import './globals.css'
import { Provider } from 'app/provider'
import { ApolloWrapper } from './ApolloWrapper'

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-background-dark">
      <body className="min-h-screen bg-background-dark text-slate-100">
        <ApolloWrapper>
          <Provider>
            <StylesProvider>{children}</StylesProvider>
          </Provider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
